### ISSUE TITLE
Passwort vergessen

### ISSUE THREAD

**Issue by chriza** [heimrichhannot/contao-notification_center_plus#1]
Hallo,

vielen Dank für die Erweiterung des Notification Centers.
Ich habe diese sogleich eingesetzt.
Bei der Passwort vergessen Funktion habe ich folgenden Fehler beim Erstellen des PW-Zurücksetzen-Links gefunden.
http://domain.tld/passwort-zuruecksetzen?token=4a539485d9904538cd93a0c174922fd2.html

Ich denke, .html sollte vor dem ?token= stehen.

**Comment by Defcon0** [comment]
Welche Versionen (Contao, notification_center und notification_center_plus) nutzt du? Mit den aktuellen Versionen und Contao 3.5.12 klappt es wunderbar.

**Comment by chriza** [comment]
Hi,

ich benutze Contao 3.5.12 mit theme+ und isotope (kleine Auswahl).

Beste Grüße

Christoph Zander

Von: Defcon0 [mailto:notifications@github.com] 
Gesendet: Mittwoch, 8. Juni 2016 16:38
An: heimrichhannot/contao-notification_center_plus
Cc: chriza; Author
Betreff: Re: [heimrichhannot/contao-notification_center_plus] Passwort vergessen (#1)

Welche Versionen (Contao, notification_center und notification_center_plus) nutzt du? Mit den aktuellen Versionen und Contao 3.5.12 klappt es wunderbar.

**Comment by Defcon0** [comment]
Mhm, da ich die normale Contao-Funktion \Controller::generateFrontendUrl nutze, sollte der Fehler in deiner Konfiguration liegen. Am besten ist es, du debuggst dich mal kurz mit XDebug da durch oder schreibst dir Testausgaben in die Moduldatei.

**Comment by KaiserCh** [comment]
Ich kann den Fehler bestätigen, habe aber auch noch einen begründeten Verdacht, warum er auftritt.
Wenn mich nicht alles täuscht sollte der 2. Parameter von \Controller::generateFrontendUrl() nicht in der Form "?key=value" sein, sondern "key/value". Je nachdem, ob Alias-Handling aktiv ist (Standard) wurde oder mutwillig abgeschaltet wurde, greifen wahlweise 
https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Controller.php#L1154
oder
https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Controller.php#L1163-L1168
