### ISSUE TITLE
Issue with Password lost / Contao 4.13.12 / PHP 8.0.25

### ISSUE THREAD

**Issue by marmeladenmopser** [heimrichhannot/contao-notification_center_plus#2]
I have an issue when i call the password lost site using the module "Passwort vergessen Plus (Benachrichtigungscenter)".

The logfile says:
request.CRITICAL: Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\ClassNotFoundError: "Attempted to load class "Request" from namespace "HeimrichHannot\Request". Did you forget a "use" statement for e.g. "Symfony\Component\HttpFoundation\Request" or "Nyholm\Psr7\Request"?" at /var/www/vhosts/xxx/httpdocs/vendor/heimrichhannot/contao-notification_center_plus/modules/ModulePasswordNotificationCenterPlus.php line 31 {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\ClassNotFoundError(code: 0): Attempted to load class \"Request\" from namespace \"HeimrichHannot\\Request\".\nDid you forget a \"use\" statement for e.g. \"Symfony\\Component\\HttpFoundation\\Request\" or \"Nyholm\\Psr7\\Request\"? at /var/www/vhosts/xxx/httpdocs/vendor/heimrichhannot/contao-notification_center_plus/modules/ModulePasswordNotificationCenterPlus.php:31)"} []

contao-notification_center_plus Version 1.6.2
Notification Center Version 1.6.14

**Comment by koertho** [comment]
Oh, there seems to be a missing dependency for https://github.com/heimrichhannot/contao-request.

Can you tell me what's your point of using this bundle? (I ask cause this is a old not very good maintained bundle :) )

**Comment by koertho** [comment]
Fixed in 1.6.3
