### ISSUE TITLE
Attachement broken

### ISSUE THREAD

**Issue by LupusVII** [heimrichhannot/contao-notification_center_plus#3]
Hi,
I don't really know what happens, but in the function `getAttachments()` in `vendor/heimrichhannot/contao-notification_center_plus/library/NotificationCenterPlus/MessageDraft/EmailMessageDraft.php` does not retrieve the attachment tokens properly.

Before I install the bundle, it worked and after that, the attachments disappeared. If I comment this function, everything works again so it looks like the issue is located there. Probably a path issue?
Thanks!

**Comment by koertho** [comment]
Hi, first of all: please always provide contao-, php- and bundle-version. 

Why / What for you're using this extension?

Issue should be fixed in 1.6.3.

**Comment by LupusVII** [comment]
Sorry for the missing information.
PHP 7.4, Contao 4.9.38 and bundle 1.6.2

I use the bundle for the conditional tokens inside the Notification center.
It's fixed in 1.6.3, thank you sir!
