### ISSUE TITLE
PHP 8.1

### ISSUE THREAD

**Issue by Olli** [heimrichhannot/contao-notification_center_plus#4]
Wäre es möglich, das Paket auch für PHP 8.1 frei zu geben?

**Comment by koertho** [comment]
Ist es schon ;)

**Comment by Olli** [comment]
Ach stimmt. Dann will es nicht installieren, weil haste-plus mit PHP 8.1 nicht will.

**Comment by koertho** [comment]
Haste plus ist auch schon für 8+ freigegeben.

**Comment by Olli** [comment]
Vielleicht wird die falsche Version vom haste-plus angefordert

```
 Problem 1
    - heimrichhannot/contao-notification_center_plus[1.6.0, ..., 1.6.3] require heimrichhannot/contao-haste_plus ~1.4 -> satisfiable by heimrichhannot/contao-haste_plus[1.4.0, ..., 1.15.12].
    - heimrichhannot/contao-haste_plus[1.4.0, ..., 1.15.12] require codefog/contao-haste >=4.10,<5-dev -> found codefog/contao-haste[4.10.0, ..., 4.25.23] but these were not loaded, likely because it conflicts with another require.
    - heimrichhannot/contao-haste_plus[1.6.20, ..., 1.6.59] require php ~5.6 || ^7.0 -> your php version (8.1.13.0) does not satisfy that requirement.
    - heimrichhannot/contao-haste_plus[1.6.91, ..., 1.14.1] require php ~5.4 || ~7.0 -> your php version (8.1.13.0) does not satisfy that requirement.
    - Root composer.json requires heimrichhannot/contao-notification_center_plus ^1.6 -> satisfiable by heimrichhannot/contao-notification_center_plus[1.6.0, 1.6.1, 1.6.2, 1.6.3].
   

```

**Comment by koertho** [comment]
Du könntest testweise die neuste Version von Haste Plus als abhängigkeit eintragen, dann bekommst du vermutlich ne klarere Fehlermeldung

**Comment by Olli** [comment]
Ok ich habe nur mal haste-plus versucht zu installieren - leider nicht sehr aussagekräftig.
```

  Problem 1
    - heimrichhannot/contao-haste_plus[1.15.0, ..., 1.15.12] require codefog/contao-haste >=4.10,<5-dev -> found codefog/contao-haste[4.10.0, ..., 4.25.23] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires heimrichhannot/contao-haste_plus ^1.15 -> satisfiable by heimrichhannot/contao-haste_plus[1.15.0, ..., 1.15.12].
```

Ich habe dann Haste in Version 4.25.23 installiert und das ging nicht weil die aktuelle Version vom NotificationCenter Haste 5. braucht (was haste-plus aber nicht möchte).

**Comment by koertho** [comment]
Haste-Plus funktioniert nur mit haste 4. Da müsstest du den notification center downgraden. Das ist die einzige Lösung aktuell. Hat aber effektiv keinen Nachteil, da die einzige echte Neuerung in NC 1.7 meines Wissens eben Haste 5 ist.

**Comment by Olli** [comment]
Alles klar danke für den Hinweis. Ich probiers
