### ISSUE TITLE
Warning: Undefined array key "inputType"

### ISSUE THREAD

**Issue by tognit** [heimrichhannot/contao-notification_center_plus#5]
Contao 4.13.36
Notification 1.7.5
NotificationPlus 1.6.3

Hallo zusammen
Wenn ein Member im Frontend eingeloggt ist und ein Formular versendet, kommt die nachfolgende Fehlermeldung.

`Warning: Undefined array key "inputType"`
![error_meldung](https://github.com/heimrichhannot/contao-notification_center_plus/assets/1794459/cd1162f4-a1c3-4b75-945d-e88874de8bde)

Wenn die Erweiterung nicht installiert ist, funktioniert das versenden und die Benachrichtigung funktioniert auch.

**Comment by koertho** [comment]
Hallo, danke für die Meldung!
Der Fehler ist jedoch nur ein Warning, tritt also nur im Dev-Mode auf.
